### ISSUE TITLE
Code will not compile

### ISSUE THREAD

**Issue by andersjh** [Apress/pro-spring-5#1]
updated spring resources to current version since it first complained about that.  Then still getting:

 This project is a collection of simple code samples. It is meant to be used tog
ether with the "Spring Pro, Fifth Edition"  published by Apress in order to lear
n and practice with all Spring Web libraries.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\anderjh\Downloads\pro-spring-5-master\chapter02\hello-world
\build.gradle' line: 7

* What went wrong:
A problem occurred evaluating project ':chapter02:hello-world'.
> Could not resolve all files for configuration ':chapter02:hello-world:compile'
.
   > Could not resolve ch.qos.logback:logback-classic:1.2.3.
     Required by:
         project :chapter02:hello-world
      > Could not resolve ch.qos.logback:logback-classic:1.2.3.
         > Could not get resource 'https://repo.maven.apache.org/maven2/ch/qos/l
ogback/logback-classic/1.2.3/logback-classic-1.2.3.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/ch/qos/logback
/logback-classic/1.2.3/logback-classic-1.2.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path building f
ailed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fin
d valid certification path to requested target
      > Could not resolve ch.qos.logback:logback-classic:1.2.3.
         > Could not get resource 'https://repo.spring.io/libs-snapshot/ch/qos/l
ogback/logback-classic/1.2.3/logback-classic-1.2.3.pom'.
            > Could not GET 'https://repo.spring.io/libs-snapshot/ch/qos/logback
/logback-classic/1.2.3/logback-classic-1.2.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path building f
ailed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fin
d valid certification path to requested target
      > Could not resolve ch.qos.logback:logback-classic:1.2.3.
         > Could not get resource 'https://repo.spring.io/libs-milestone/ch/qos/
logback/logback-classic/1.2.3/logback-classic-1.2.3.pom'.
            > Could not GET 'https://repo.spring.io/libs-milestone/ch/qos/logbac
k/logback-classic/1.2.3/logback-classic-1.2.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path building f
ailed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fin
d valid certification path to requested target
   > Could not resolve org.springframework:spring-core:5.0.2.RELEASE.
     Required by:
         project :chapter02:hello-world > org.springframework:spring-context:5.0
.2.RELEASE
         project :chapter02:hello-world > org.springframework:spring-context:5.0
.2.RELEASE > org.springframework:spring-aop:5.0.2.RELEASE
         project :chapter02:hello-world > org.springframework:spring-context:5.0
.2.RELEASE > org.springframework:spring-beans:5.0.2.RELEASE
         project :chapter02:hello-world > org.springframework:spring-context:5.0
.2.RELEASE > org.springframework:spring-expression:5.0.2.RELEASE
      > Could not resolve org.springframework:spring-core:5.0.2.RELEASE.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/spri
ngframework/spring-core/5.0.2.RELEASE/spring-core-5.0.2.RELEASE.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/springfra
mework/spring-core/5.0.2.RELEASE/spring-core-5.0.2.RELEASE.pom'.
               > sun.security.validator.ValidatorException: PKIX path building f
ailed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fin
d valid certification path to requested target
      > Could not resolve org.springframework:spring-core:5.0.2.RELEASE.
         > Could not parse POM http://repo.spring.io/release/org/springframework
/spring-core/5.0.2.RELEASE/spring-core-5.0.2.RELEASE.pom
            > Could not resolve io.netty:netty-bom:4.1.17.Final.
               > Could not resolve io.netty:netty-bom:4.1.17.Final.
                  > Could not get resource 'https://repo.maven.apache.org/maven2
/io/netty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                     > Could not GET 'https://repo.maven.apache.org/maven2/io/ne
tty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                        > sun.security.validator.ValidatorException: PKIX path b
uilding failed: sun.security.provider.certpath.SunCertPathBuilderException: unab
le to find valid certification path to requested target
               > Could not resolve io.netty:netty-bom:4.1.17.Final.
                  > Could not get resource 'https://repo.spring.io/libs-snapshot
/io/netty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                     > Could not GET 'https://repo.spring.io/libs-snapshot/io/ne
tty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                        > sun.security.validator.ValidatorException: PKIX path b
uilding failed: sun.security.provider.certpath.SunCertPathBuilderException: unab
le to find valid certification path to requested target
               > Could not resolve io.netty:netty-bom:4.1.17.Final.
                  > Could not get resource 'https://repo.spring.io/libs-mileston
e/io/netty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                     > Could not GET 'https://repo.spring.io/libs-milestone/io/n
etty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                        > sun.security.validator.ValidatorException: PKIX path b
uilding failed: sun.security.provider.certpath.SunCertPathBuilderException: unab
le to find valid certification path to requested target
      > Could not resolve org.springframework:spring-core:5.0.2.RELEASE.
         > Could not get resource 'https://repo.spring.io/libs-snapshot/org/spri
ngframework/spring-core/5.0.2.RELEASE/spring-core-5.0.2.RELEASE.pom'.
            > Could not HEAD 'https://repo.spring.io/libs-snapshot/org/springfra
mework/spring-core/5.0.2.RELEASE/spring-core-5.0.2.RELEASE.pom'.
               > sun.security.validator.ValidatorException: PKIX path building f
ailed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fin
d valid certification path to requested target
      > Could not resolve org.springframework:spring-core:5.0.2.RELEASE.
         > Could not parse POM http://repo.spring.io/milestone/org/springframewo
rk/spring-core/5.0.2.RELEASE/spring-core-5.0.2.RELEASE.pom
            > Could not resolve io.netty:netty-bom:4.1.17.Final.
               > Could not resolve io.netty:netty-bom:4.1.17.Final.
                  > Could not get resource 'https://repo.maven.apache.org/maven2
/io/netty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                     > Could not GET 'https://repo.maven.apache.org/maven2/io/ne
tty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                        > sun.security.validator.ValidatorException: PKIX path b
uilding failed: sun.security.provider.certpath.SunCertPathBuilderException: unab
le to find valid certification path to requested target
               > Could not resolve io.netty:netty-bom:4.1.17.Final.
                  > Could not get resource 'https://repo.spring.io/libs-snapshot
/io/netty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                     > Could not GET 'https://repo.spring.io/libs-snapshot/io/ne
tty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                        > sun.security.validator.ValidatorException: PKIX path b
uilding failed: sun.security.provider.certpath.SunCertPathBuilderException: unab
le to find valid certification path to requested target
               > Could not resolve io.netty:netty-bom:4.1.17.Final.
                  > Could not get resource 'https://repo.spring.io/libs-mileston
e/io/netty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                     > Could not GET 'https://repo.spring.io/libs-milestone/io/n
etty/netty-bom/4.1.17.Final/netty-bom-4.1.17.Final.pom'.
                        > sun.security.validator.ValidatorException: PKIX path b
uilding failed: sun.security.provider.certpath.SunCertPathBuilderException: unab
le to find valid certification path to requested target
      > Could not resolve org.springframework:spring-core:5.0.2.RELEASE.
         > Could not get resource 'https://repo.spring.io/libs-milestone/org/spr
ingframework/spring-core/5.0.2.RELEASE/spring-core-5.0.2.RELEASE.pom'.
            > Could not HEAD 'https://repo.spring.io/libs-milestone/org/springfr
amework/spring-core/5.0.2.RELEASE/spring-core-5.0.2.RELEASE.pom'.
               > sun.security.validator.ValidatorException: PKIX path building f
ailed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fin
d valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

**Comment by iuliana** [comment]
Hi, 

I just compiled all sources from the root of the project  of the project using:
`gradle clean build -c test`

I did receive a few warnings, but the project did compile:
`$ gradle clean build -x test
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
 This project is a collection of simple code samples. It is meant to be used together with the "Spring Pro, Fifth Edition"  published by Apress in order to learn and practice with all Spring Web libraries. 

> Configure project :chapter05:aspectj-aspects 
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
        at build_9bibv1bapeflwqgpf3ejff9rm.run(/Users/iuliana.grajdeanu/temp/pro-spring-5/chapter05/aspectj-aspects/build.gradle:17)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Task :chapter03:collections:compileJava 
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :chapter04:disposable-bean:compileJava 
Note: /Users/iuliana.grajdeanu/temp/pro-spring-5/chapter04/disposable-bean/src/main/java/com/apress/prospring5/ch4/DestructiveBeanWithInterface.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter04:initializing-bean-destroy:compileJava 
Note: /Users/iuliana.grajdeanu/temp/pro-spring-5/chapter04/initializing-bean-destroy/src/main/java/com/apress/prospring5/ch4/DestructiveBean.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter04:post-construct-pre-destroy:compileJava 
Note: /Users/iuliana.grajdeanu/temp/pro-spring-5/chapter04/post-construct-pre-destroy/src/main/java/com/apress/prospring5/ch4/DestructiveBeanWithJSR250.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter05:aop-hello-world:compileJava 
/Users/iuliana.grajdeanu/temp/pro-spring-5/chapter05/aop-hello-world/src/main/java/com/apress/prospring5/ch5/introduction/IsModifiedMixin.java:31: warning: non-varargs call of varargs method with inexact argument type for last parameter;
                    Object oldVal = getter.invoke(invocation.getThis(),null);
                                                                       ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
/Users/iuliana.grajdeanu/temp/pro-spring-5/chapter05/aop-hello-world/src/main/java/com/apress/prospring5/ch5/introduction/IsModifiedMixin.java:58: warning: non-varargs call of varargs method with inexact argument type for last parameter;
            getter = setter.getDeclaringClass().getMethod(getterName, null);
                                                                      ^
  cast to Class<?> for a varargs call
  cast to Class<?>[] for a non-varargs call and to suppress this warning
2 warnings

> Task :chapter08:jpa-criteria:generateQueryDSL 
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.10.Final

> Task :chapter08:jpa-criteria:compileJava 
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.10.Final

> Task :chapter18:batch-boot:compileJava 
Note: /Users/iuliana.grajdeanu/temp/pro-spring-5/chapter18/batch-boot/src/main/java/com/apress/prospring5/ch18/BatchConfig.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :chapter18:batch-cfg:compileJava 
Note: /Users/iuliana.grajdeanu/temp/pro-spring-5/chapter18/batch-cfg/src/main/java/com/apress/prospring5/ch18/config/BatchConfig.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :chapter18:integration-cfg:compileJava 
Note: /Users/iuliana.grajdeanu/temp/pro-spring-5/chapter18/integration-cfg/src/main/java/com/apress/prospring5/ch18/config/BatchConfig.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.


BUILD SUCCESSFUL in 52s
535 actionable tasks: 405 executed, 130 up-to-date`

Are you behind a firewall that prevents downloading artifacts from the Spring repositories? Or, is your maven installation filtered by a mirror?

Please give me more details. I cannot reproduce this.

**Comment by andersjh** [comment]
Thanks for the prompt response.  I just did as you did on a personal device and all is well.  So the work computer is causing the issues.  I can just use my own computer for going through this book.

Thanks so much!

**Comment by iuliana** [comment]
Hi, 

I deleted my previous comment, because I realized you were using a different Spring Version. 
I updated the sources and changed Spring version to 5.0.2.RELEASE as well. I also changed Spring Boot version to 2.0.0.M7. 

I rebuild the project using
 `gradle --refresh-dependencies clean build -x test `
and it completed successfully. (See log [here](https://pastebin.com/7nh9Eq3h))

Also, after loading the project in IntelliJ IDEA,  all looks good as well. 

I will push the new versions as well. 

I am glad all works well now. 
Cheers!

**Comment by andersjh** [comment]
You are awesome!!!

**Comment by vukroxKrd** [comment]
Hey there!
I am having a similar problem. When I cloned the project and try to "Load Gradle Changes" using top rigth icon in intelliJ it gives me the following error message:
`Build file 'C:\Projects\Apress\Spring\ProSpring5\chapter02\chapter02.gradle' line: 7

A problem occurred evaluating project ':chapter02'.
> Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.`

At the same time when I build this project with Gradle comands from readme in CLI on Windows/inside Intellij terminal the build is successfull.

IntelliJ version: "Build #IU-223.8617.56, built on January 26, 2023"
Gradle version: 5.6
JDK version: 1.8

Is there anything I can do to make it work, could you please help?

**Comment by iuliana** [comment]
Hello @vukroxKrd , 

The error is pretty obvious, the Gradle version does not support the `compile` configuration. This project is quite old but I remember having issues as well, I think they switched from `compile` to `implementation` between two 5.x versions. Try  an earlier Gradle version, like Gradle 5.0 or 5.1. 

Let me know if it doesn't work and I'll try to rebuild this project myself to identify a proper version. 

Cheers!
Iuliana
