### ISSUE TITLE
Lack of javadocs with usage of gradle wrapper

### ISSUE THREAD

**Issue by CharlesCZ** [Apress/pro-spring-5#16]
Hi,
I'm reading your book :) and want to use your code in action and It's working but I'm facing another issue that I can't get any javadocs from jars (I'm talking about spring jars, not JDK). I tried to add this code 

```
apply plugin: 'java'
apply plugin: 'idea'

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
```
to many build.gradle files also to the one with the highest hierarchy but I don't see any javadocs, for example when I want to see javadoc to annotation @SpringBootApplication I only see:

```
org.springframework.boot.autoconfigure @Target({ElementType.TYPE}) 

    @Retention(RetentionPolicy.RUNTIME) 
    @Documented 
    @Inherited 
    @SpringBootConfiguration 
    @EnableAutoConfiguration 
    @ComponentScan(excludeFilters = {@org.springframework.context.annotation.ComponentScan.Filter(type = org.springframework.context.annotation.FilterType.CUSTOM, classes = {org.springframework.boot.context.TypeExcludeFilter.class}),@org.springframework.context.annotation.ComponentScan.Filter(type = org.springframework.context.annotation.FilterType.CUSTOM, classes = {org.springframework.boot.autoconfigure.AutoConfigurationExcludeFilter.class})}) 
    public interface SpringBootApplication
    extends annotation.Annotation

      Gradle: org.springframework.boot:spring-boot-autoconfigure:2.0.6.RELEASE
```

but not documentation itself

**Comment by iuliana** [comment]
Hi Charles, 

I'm not sure this is an issue with my code. This might be an issue with your firewall not allowing the editor to get the documentation from the web.  I do not have any special configuration in the project specifically for that. 

For example, when I first installed IntelliJ IDEA, a pop-up up window required me to approve internet access for all java processes. This is so that dependencies and documentation can be downloaded freely. 

Just try reinstalling your editor, or check your firewall settings. The issue you arre experiencing has nothing to do with my code and since probably I won't be able to reproduce it, I cannot help very much. 

Cheers!
