### ISSUE TITLE
Chapter 4 section destroying beans

### ISSUE THREAD

**Issue by Affid** [Apress/pro-spring-5#24]
Why do we use ctx.destroy() in main?

It is now marked as deprecated.

May be it should be ctx.close() instead?

P.S My English is a little bad, so I may seem rude, but I don't want to be rude:)

https://github.com/Apress/pro-spring-5/blob/master/chapter04/initializing-bean-destroy/src/main/java/com/apress/prospring5/ch4/DestructiveBean.java

**Comment by iuliana** [comment]
Hello Affid, 

It is now marked as deprecated but it wasn't when I touched that code last. 
The reason you will find sometimes methods that are being called althought not needed, is to make it obvious to the person learning a framework what happens, or what is a normal lifecycle  for a bean. Because if you tell them that it is done for them, but at some point they need to customize that operation they will have to do the reasearch and reading themselves to figure out how. 

I am sorry if my answer is not clear enouh. It's like explainin to your kid how velcro works. You can tell them that it sticks, but you can also show them how it sticks.  :)

Do not worry, your English is pretty good.

And thank you for the observation. I'll remove that method call it in the next code iteration.

Cheers!

**Comment by iuliana** [comment]
Hello Affid, 

I replaced the method with `close()` in the code and added contribution mention to the erratum. 

Commit: [https://github.com/Apress/pro-spring-5/commit/07283daaf6ae419e5258007436485f256d6ed43e](https://github.com/Apress/pro-spring-5/commit/07283daaf6ae419e5258007436485f256d6ed43e)

Cheers!
Iuliana Cosmina
