### ISSUE TITLE
Error running "gradle clean build"

### ISSUE THREAD

**Issue by pula2000** [Apress/pro-spring-5#3]
I cloned the repo and ran the above command and got the below error - 
What went wrong:
A problem occurred configuring project ':chapter05:aspectj-aspects'.
> Could not resolve all files for configuration ':chapter05:aspectj-aspects:classpath'.
   > Could not resolve nl.eveoh:gradle-aspectj:1.6.
     Required by:
         project :chapter05:aspectj-aspects
      > Could not resolve nl.eveoh:gradle-aspectj:1.6.
         > Could not get resource 'https://maven.eveoh.nl/content/repositories/releases/nl/eveoh/gradle-aspectj/1.6/gradle-aspectj-1.6.pom'.
            > Could not GET 'https://maven.eveoh.nl/content/repositories/releases/nl/eveoh/gradle-aspectj/1.6/gradle-aspectj-1.6.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by iuliana** [comment]
Hello, 
Apparently the plugin has switched version and version 1.6 is no longer supported.
I updated the configuration file  and updated the **chapter05/aspectj-aspects** project because apparently separating Aspects from Java classes is no longer necessary. 

Observations: IntelliJ IDEA  still does not know how to handle aspects thus my recommendation to run the examples in the command line is to follow the next steps:
- build the whole project with `gradle clean build -x test --refresh-dependencies` (from pro-spring-5 directory)
- go to `chapter05/aspectj-aspects/`
- execute `gradle copyDependencies`
- go to: `aspectj-aspects/build/libs `
- execute `java -jar aspectj-aspects-5.0-SNAPSHOT.jar` and you should see the following:
`The Prefix
foobar!
The Suffix
foo
`
Let me know if it works and if there is anything else I need to do there. 

Cheers!
Iuliana

**Comment by pula2000** [comment]
So I ran the first command  - `gradle clean build -x test --refresh-dependencies`
from the root of the repo from command line in mac but still got the same issue.

**Comment by iuliana** [comment]
Hi, 

Apparently this issue occurs when a server changes their HTTPS SSL certificate, and your older version of java doesn’t recognize the root certificate authority (CA). If you can access the HTTPS URL in your browser then it is possible to update Java to recognize the root CA.
Please follow this link [https://developer.salesforce.com/forums/?id=9060G000000BhSjQAK](https://developer.salesforce.com/forums/?id=9060G000000BhSjQAK) and look at the reply by **IvanWu**
Another thing you can do is to create an issue for the AspectJ Gradle plugin, here is the project official page [https://github.com/eveoh/gradle-aspectj](https://github.com/eveoh/gradle-aspectj). Because its authors might be able to help since its their server that is causing the issue for you.

Another thing you can do is to just download the plugin locally, build it and use it as a dependency from your local machine. 

I cannot reproduce this issue as you can see here, and all the commands in my previous comment I tried them myself on my repository and on my computer works fine. (Build log: [https://pastebin.com/C6KJ6zE3](https://pastebin.com/C6KJ6zE3)
 
Let me know if any of the proposal above solved it for you. If you do not know how to work with the plugin locally, I can provide the instructions to do so as well.

Cheers, 
Iuliana

**Comment by iuliana** [comment]
As, the user has not come back with a feedback. I consider this issue solved.

**Comment by farazdurrani** [comment]
Hi iuliana,

Can you replace that specific aspectj with another one? that eveoh aspect j has gone awol.
