### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by drievkoo** [Apress/pro-spring-5#36]
Hi, I am unable to build the repo, I am getting this error:
```
Build file '/home/pro-spring-5/chapter02/chapter02.gradle' line: 7

A problem occurred evaluating project ':chapter02'.
> Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.
```

**Comment by iuliana** [comment]
Hello @drievkoo , 

Which version of Gradle are you using? Quotte from the README.adoc:  "This is a Gradle multi-module project. Currently it can be compiled with Gradle 5.x and JDK 8."

The 'compile' directive was removed in Gradle 6 I think and replaced with  'implementation'.   My suspicion is that you are using a more recent verrsion of Gradle and this project is pretty damn old.

Let me know if downgrading Gradle fixed your issue, although I suspect it will. ;)

Cheers,
Iuliana

**Comment by rajeevkchaubey** [comment]
Hi ,
I am still getting same issue . I did switched to Gradle 5.6.4 .
Should I try with lower versions ?

**Comment by iuliana** [comment]
Hello @rajeevkchaubey,

I just switched to Gradle 5.6.4 (your version) & JDK 8, **as the readme says**. I rebuild the full project with ` gradle clean build -x test` and everythign is fine, as proven by the below snippet. 


However, when building with tests I sawsaome test failures  by some SQL syntax for H2 configuration files that was deprecated. I upgraded H2 a while ago from `1.4.194` to `2.0.206` and I confess I did not run the full build. 

I reiterate, the build should pass without tests for **Gradle 5.x** and **JDK 8**. The second problem you are ssing is because JDK 11. 

I repeat this project is **OLD**.  anyway, I will now try to fix the SQL issues I am seeing, I'll push a fix when ready and let you know.

Cheers, 
Iuliana Cosmina

**Comment by rajeevkchaubey** [comment]
Thanks for quick reply @iuliana . I will try to switch jdk 8 and try . 

I understand this project is old , but the book is fabulous and best source of learning spring 5 for a beginner like me :) . I wish if I can fix my compile issues and keep learning :) .

Thanks!!

**Comment by iuliana** [comment]
Hello @rajeevkchaubey, 

I finally got it working. It required a hibernate upgrade as well and some additional changes, but the build now passes with  the tests as well.  Just pull the latest version of the project. 
Cheers!

P.S.: Below is my log as proof.

`
~/apress/workspace/pro-spring-5   master  gradle clean build
 This project is a collection of simple code samples. It is meant to be used together with the "Spring Pro, Fifth Edition"  published by Apress in order to learn and practice with all Spring Web libraries.

> Task :chapter03:collections:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :chapter05:aop-hello-world:compileJava
/Users/iulianacosmina/apress/workspace/pro-spring-5/chapter05/aop-hello-world/src/main/java/com/apress/prospring5/ch5/introduction/IsModifiedMixin.java:31: warning: non-varargs call of varargs method with inexact argument type for last parameter;
                    Object oldVal = getter.invoke(invocation.getThis(),null);
                                                                       ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
/Users/iulianacosmina/apress/workspace/pro-spring-5/chapter05/aop-hello-world/src/main/java/com/apress/prospring5/ch5/introduction/IsModifiedMixin.java:58: warning: non-varargs call of varargs method with inexact argument type for last parameter;
            getter = setter.getDeclaringClass().getMethod(getterName, null);
                                                                      ^
  cast to Class<?> for a varargs call
  cast to Class<?>[] for a non-varargs call and to suppress this warning
2 warnings

> Task :chapter08:jpa-criteria:compileJava
Note: Hibernate JPA 2 Static-Metamodel Generator 5.6.5.Final

> Task :chapter12:rest:compileJava
Note: /Users/iulianacosmina/apress/workspace/pro-spring-5/chapter12/rest/src/main/java/com/apress/prospring5/ch12/init/WebConfig.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter12:rest:compileTestJava
Note: /Users/iulianacosmina/apress/workspace/pro-spring-5/chapter12/rest/src/test/java/com/apress/prospring5/ch12/RestClientConfig.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter12:secure-rest:compileJava
Note: /Users/iulianacosmina/apress/workspace/pro-spring-5/chapter12/secure-rest/src/main/java/com/apress/prospring5/ch12/init/WebConfig.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter12:secure-rest:compileTestJava
Note: /Users/iulianacosmina/apress/workspace/pro-spring-5/chapter12/secure-rest/src/test/java/com/apress/prospring5/ch12/RestClientConfig.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter13:integration-test:test
23:03:51.519 [Thread-4] INFO  o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
Hibernate: drop table if exists singer CASCADE

> Task :chapter13:junit5-test:test
23:03:54.859 [Thread-4] INFO  o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
Hibernate: drop table if exists singer CASCADE

> Task :chapter15:jmx:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter16:singer-webapp-boot:compileJava
Note: /Users/iulianacosmina/apress/workspace/pro-spring-5/chapter16/singer-webapp-boot/src/main/java/com/apress/prospring5/ch16/WebSecurityConfig.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter17:stomp-cfg:compileJava
Note: /Users/iulianacosmina/apress/workspace/pro-spring-5/chapter17/stomp-cfg/src/main/java/com/apress/prospring5/ch17/config/WebSocketConfig.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter18:batch-boot:compileJava
Note: /Users/iulianacosmina/apress/workspace/pro-spring-5/chapter18/batch-boot/src/main/java/com/apress/prospring5/ch18/BatchConfig.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :chapter18:batch-cfg:compileJava
Note: /Users/iulianacosmina/apress/workspace/pro-spring-5/chapter18/batch-cfg/src/main/java/com/apress/prospring5/ch18/config/BatchConfig.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :chapter18:boot-tests:test
23:05:39.898 [Thread-5] INFO  o.s.w.c.s.GenericWebApplicationContext - Closing org.springframework.web.context.support.GenericWebApplicationContext@7f6de482: startup date [Wed Feb 09 23:05:29 GMT 2022]; root of context hierarchy

> Task :chapter18:integration-cfg:compileJava
Note: /Users/iulianacosmina/apress/workspace/pro-spring-5/chapter18/integration-cfg/src/main/java/com/apress/prospring5/ch18/config/BatchConfig.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :chapter18:webflux:test
23:05:45.351 [Thread-4] INFO  o.s.c.s.GenericApplicationContext - Closing org.springframework.context.support.GenericApplicationContext@361e7dc7: startup date [Wed Feb 09 23:05:42 GMT 2022]; root of context hierarchy
23:05:45.352 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'lifecycleProcessor'
23:05:45.352 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@5776b159: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,serverConfig,testConfig,dataServiceConfig,reactiveSingerRepoImpl,DBInitializer,singerHandler,dataSource,hibernateProperties,transactionManager,jpaVendorAdapter,entityManagerFactory,org.springframework.data.jpa.repository.config.JpaRepositoryConfigExtension#0,emBeanDefinitionRegistrarPostProcessor,jpaMappingContext,jpaContext,singerRepository,server,testClient,org.springframework.orm.jpa.SharedEntityManagerCreator#0]; root of factory hierarchy
23:05:45.352 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'jpaMappingContext': [singerRepository]
23:05:45.352 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'singerRepository': [reactiveSingerRepoImpl, DBInitializer]
23:05:45.352 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'reactiveSingerRepoImpl': [singerHandler]
23:05:45.352 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'singerHandler': [server]
23:05:45.352 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'server': [testConfig]
23:05:45.352 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean '(inner bean)#35dd916d': [singerRepository]
23:05:45.352 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean '(inner bean)#13e60abe': [(inner bean)#35dd916d]
23:05:45.353 [Thread-4] DEBUG o.s.b.f.s.DisposableBeanAdapter - Invoking destroy() on bean with name 'jpaMappingContext'
23:05:45.353 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'entityManagerFactory': [transactionManager, org.springframework.orm.jpa.SharedEntityManagerCreator#0]
23:05:45.353 [Thread-4] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'org.springframework.orm.jpa.SharedEntityManagerCreator#0': [jpaContext]
23:05:45.353 [Thread-4] DEBUG o.s.b.f.s.DisposableBeanAdapter - Invoking destroy method 'close' on bean with name 'entityManagerFactory'
23:05:45.353 [Thread-4] INFO  o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
Hibernate: drop table if exists singer CASCADE
23:05:45.354 [Thread-4] DEBUG o.s.j.d.SimpleDriverDataSource - Creating new JDBC Driver Connection to [jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false]
23:05:45.355 [Thread-4] DEBUG o.s.b.f.s.DisposableBeanAdapter - Invoking destroy method 'shutdown' on bean with name 'dataSource'
23:05:45.355 [Thread-4] INFO  o.s.j.d.e.EmbeddedDatabaseFactory - Shutting down embedded database: url='jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'
23:05:45.355 [Thread-4] DEBUG o.s.j.d.SimpleDriverDataSource - Creating new JDBC Driver Connection to [jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false]

> Task :chapter18:webflux-boot:compileTestJava
Note: /Users/iulianacosmina/apress/workspace/pro-spring-5/chapter18/webflux-boot/src/test/java/com/apress/prospring5/ch18/SingerHandlerTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :chapter18:webflux-boot:test
23:06:21.930 [Thread-13] INFO  o.s.w.c.s.GenericWebApplicationContext - Closing org.springframework.web.context.support.GenericWebApplicationContext@3095051c: startup date [Wed Feb 09 23:06:07 GMT 2022]; root of context hierarchy
23:06:21.933 [Thread-13] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
23:06:21.934 [Thread-13] INFO  o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
23:06:21.938 [Thread-13] INFO  c.a.i.i.TransactionServiceImp - Transaction Service: Entering shutdown (false, 9223372036854775807)...
23:06:21.943 [Thread-13] INFO  c.a.d.p.ConnectionPool - atomikos connection pool 'dataSource': destroying pool...

BUILD SUCCESSFUL in 3m 37s
593 actionable tasks: 593 executed             
`

**Comment by rajeev-variant** [comment]
Thanks @iuliana !

**Comment by Norlandz** [comment]
1 . 
(For me, the java version, java8u331 is not working, but java8u20 is fine... Just saying.)
2 .
For the Error with `import javax.annotation.Resource cannot be resolved` see [import javax.annotation.* cannot be resolved](https://stackoverflow.com/questions/51630397/import-javax-annotation-cannot-be-resolved-in-eclipses-java-10-compiler)
  1. Download `javax.annotation-api-1.3.2.jar` 
  2. Add that dependency to the `build.gradle` in the `Top Parent (Master) Project` 
  eg:
``` groovy
subprojects {
	version '5.0-SNAPSHOT'
	apply plugin: 'java'
	
	repositories {
		mavenLocal()
		mavenCentral()
		maven { url "http://repo.spring.io/release" }
		maven { url "http://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/libs-snapshot" }
		maven { url "http://repo.spring.io/milestone" }
		maven { url "https://repo.spring.io/libs-milestone" }
	}
	dependencies {
		compile files('C:/Users/UserName/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar')
	}
}
```

**Comment by iuliana** [comment]
@Norlandz you are right about the `javax.annotation-api`, not sure the project built without it until now. I wil add it in. 
Good catch, thank you!
